version: '3.1'

services:

  mongodb:    
    image: bitnami/mongodb:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  todo-server:
    build: ./server
    restart: always
    ports:
      - 5000:80
    environment:
      MongoDB__Host: mongodb
    depends_on:
      - mongodb

  todo-client:
    build: ./client
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 8080:80
    depends_on:
      - todo-server
