apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-chart-svc
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      run: server-chart
  serviceName: server-chart-svc
  template:
    metadata:
      labels:
        run: server-chart
    spec:
      containers:
      - name: server-chart-svc        
        image: {{ .Values.image }}
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: server-storage
          mountPath: /data/mongo
      volumes:
      - name: server-storage
        emptyDir: {}